swagger: "2.0"
info:
  version: "1.0.0"
  title: "myDeben"
  contact:
    email: "youssuf.radi@deemalab.com"
host: "localhost:3000"
basePath: "/api"
tags:
- name: "Auth"
  description: "Used for user to retrieve access token needed for further identification"
- name: "store"
  description: "All APIs related to the user"
- name: "user"
  description: "All APIs related to the web admin"
schemes:
- "http"
paths:
  /auth/user/signin:
    post:
      tags:
      - "Auth"
      summary: "User Sign In"
      description: "Returns a token for user to be used in further identification"
      operationId: "userSignIn"
      consumes:
      - "application/json"
      produces:
      - "application/json"
      parameters:
      - in: "body"
        name: "body"
        description: "User email and password for sign in"
        required: true
        schema:
          type: "object"
          required:
          - "email"
          - "password"
          properties:
            email:
              type: "string"
              format: "email"
            password:
              type: "string"
              format: "password"
      responses:
        200:
          description: "Successfully Logged In"
          type: "object"
          properties:
            detail:
              type: "string" 
            auth:
              type: "boolean"
            token:
              type: "string"
        400:
          description: "Bad request or Required fields not stated"
        401:
          description: "Wrong Username or Password used"
          
  /auth/user/signup:
    post:
      tags:
      - "Auth"
      summary: "User Sign Up"
      description: "Creates a new user in the database"
      operationId: "userSignUp"
      consumes:
      - "application/json"
      produces:
      - "application/json"
      parameters:
      - in: "body"
        name: "body"
        description: "User email, name and password to register"
        required: true
        schema:
          type: "object"
          required:
          - "email"
          - "name"
          - "password"
          properties:
            email:
              type: "string"
              format: "email"
            name:
              type: "string"
            password:
              type: "string"
              format: "password"
      responses:
        200:
          description: "Successfully Signed Up"
          type: "object"
          properties:
            detail:
              type: "string" 
            success:
              type: "boolean"
        400:
          description: "Email entered not available or Required fields not satisfied"
        401:
          description: "Wrong Username or Password used"

  /auth/store/signin:
    post:
      tags:
      - "Auth"
      summary: "Store Sign In"
      description: "Returns a token for store to be used in further identification"
      operationId: "storeSignIn"
      consumes:
      - "application/json"
      produces:
      - "application/json"
      parameters:
      - in: "body"
        name: "body"
        description: "User email and password for sign in"
        required: true
        schema:
          type: "object"
          required:
          - "email"
          - "password"
          properties:
            email:
              type: "string"
              format: "email"
            password:
              type: "string"
              format: "password"
      responses:
        200:
          description: "Successfully Logged In"
          type: "object"
          properties:
            detail:
              type: "string" 
            auth:
              type: "boolean"
            token:
              type: "string"
        400:
          description: "Bad request or Required fields not stated"
        401:
          description: "Wrong Username or Password used"

  /auth/store/signup:
    post:
      tags:
      - "Auth"
      summary: "Store Sign Up"
      description: "Creates a new store in the database"
      operationId: "storeSignUp"
      consumes:
      - "application/json"
      produces:
      - "application/json"
      parameters:
      - in: "body"
        name: "body"
        description: "Store email, name and password to register"
        required: true
        schema:
          type: "object"
          required:
          - "email"
          - "name"
          - "password"
          properties:
            email:
              type: "string"
              format: "email"
            name:
              type: "string"
            password:
              type: "string"
              format: "password"
      responses:
        200:
          description: "Successfully Signed Up"
          type: "object"
          properties:
            detail:
              type: "string" 
            success:
              type: "boolean"
        400:
          description: "Email entered not available or Required fields not satisfied"
        401:
          description: "Wrong Username or Password used"
securityDefinitions:
  ApiKeyAuth:
    type: apiKey
    in: header
    name: x-access-token
                